### Create a new report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "Toyota",
  "model": "Highlander",
  "year": 2003,
  "mileage": 430000,
  "lng": 0,
  "lat": 0,
  "price": 3000
}

### Approve an existing request
PATCH http://localhost:3000/reports/6
Content-Type: application/json

{
  "approved": true
}

### Get an estimate for an existing vehicle
GET http://localhost:3000/reports?make=Toyota&model=Highlander&year=2003&mileage=230000&lng=0&lat=0